<?php include('Header.php'); ?>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Prestamos</h1>
        <div class="btn-toolbar mb-2 mb-md-0 ">
        </div>
      </div>
      <div class="table-responsive table-scroll ">
        <table class="table table-striped table-sm ">
          <thead>
            <tr>
              <th>Id_Prestamo</th>
              <th>Hora de inicio</th>
              <th>Hora de entrega</th>
              <th>01/01/2021</th>
              <th>Estado</th>
            </tr>
          </thead>
          <tbody >
            <tr>
              <td>0000_1</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>En curso</td>
            </tr>
            <tr>
              <td>0000_2</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>Finalizado</td>
            </tr>
            <tr>
              <td>0000_3</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>Finalizado</td>
            </tr>
            <tr>
              <td>0000_4</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>En curso</td>
            </tr>
            <tr>
              <td>0000_5</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>Finalizado</td>
            </tr>
            <tr>
              <td>0000_6</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>En curso</td>
            </tr>
            <tr>
              <td>0000_7</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>Finalizado</td>
            </tr>
            <tr>
              <td>0000_8</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>En curso</td>
            </tr>
            <tr>
              <td>0000_9</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>Finalizado</td>
            </tr>
            <tr>
              <td>0001_0</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>En curso</td>
            </tr>
            <tr>
              <td>0001_1</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>Finalizado</td>
            </tr>
            <tr>
              <td>0001_2</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>En curso</td>
            </tr>
            <tr>
              <td>0001_3</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>En curso</td>
            </tr>
            <tr>
              <td>0001_4</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>Finalizado</td>
            </tr>
            <tr>
              <td>0001_5</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>Finalizado</td>
            </tr>
            <tr>
              <td>0001_6</td>
              <td>12:00</td>
              <td>14:00</td>
              <td>01/01/2021</td>
              <td>En curso</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>

<?php include('Footer.php'); ?>
